language: python
python:  
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest 
  - python -m pytest --cov=api tests/
# Coveralls to show test coverage of the modules
after_success:
  - coveralls
# deploy on heroku
deploy:
  provider: heroku
  api_key:
    secure: 5aa6788f-2d78-44de-93fb-5eae5f207d96
  app: tasks-api-ben